namespace pc_utils{
#define define(type)    PC_UTILS_TEMPLATE_SPECIALIZATIONS(type)

PC_UTILS_TEMPLATE_SPECIALIZATION_LIST

#undef define
}

#define MERGED(T)   PC_UTILS_LINK_HELPER_CPP(T)
MERGED(PC_UTILS_CLASS_BASE_TYPE)